### PR TITLE
feat: no floating promises

### PR DESCRIPTION
**Pull request by naseemkullah**
closes https://github.com/google/gts/issues/546

### CODE REVIEW

**Comment by naseemkullah** [comment]
@bcoe ptal 🙏  best lint rule in the world right here

**Comment by naseemkullah** [comment]
Hi @sofisl, can you please take a look at this? Thanks

**Comment by naseemkullah** [comment]
someone please take a look please

**Comment by danielbankhead** [comment]
@naseemkullah - I'll discuss this with the team and get back to you

**Comment by danielbankhead** [comment]
Hey @naseemkullah, the PR looks great - thanks for the contribution. To not immediately break anyone do you mind changing the rule to `warn` rather than `error`? I can create a follow-up to change it to `error` in the next major release.

**Comment by naseemkullah** [comment]
Thanks @danielbankhead - certainly, changed to `warn` for now and we can change it to `error` upon next major release if all's well.

**Review by danielbankhead — APPROVED** [review]

**Pull request merged**
