### PR TITLE
build: Configure Cirrus CI for Windows

### PR DESCRIPTION
**Pull request by fkorotkov**
I saw #331 and decided to take a look. 

@JustinBeckwith @ofrobots PTAL

### CODE REVIEW

**Comment by fkorotkov** [comment]
There are some tests failing though (see https://cirrus-ci.com/build/5057230643134464):

```bash
8 failing
  1) 🚰 kitchen sink
       it should run init:
     Error: ENOENT: no such file or directory, access 'C:\Users\ContainerAdministrator\AppData\Local\Temp\tmp-3476LVq1vEY8QONS/kitchen/tsconfig.json'
      at Object.accessSync (fs.js:197:3)
      at Context.it (test\test-kitchen.ts:18:21)
      at processImmediate (internal/timers.js:443:21)
  2) 🚰 kitchen sink
       should use as a non-locally installed module:
     Error: ENOENT: no such file or directory, open 'C:\Users\ContainerAdministrator\AppData\Local\Temp\tmp-3476hs3z7TZDuQd0/kitchen/tsconfig.json'
      at Object.openSync (fs.js:448:3)
      at Object.readFileSync (fs.js:348:35)
      at Context.it (test\test-kitchen.ts:36:1)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
  3) 🚰 kitchen sink
       should terminate generated json files with newline:
     Error: ENOENT: no such file or directory, open 'C:\Users\ContainerAdministrator\AppData\Local\Temp\tmp-3476LVq1vEY8QONS/kitchen/tsconfig.json'
      at Object.openSync (fs.js:448:3)
      at Object.readFileSync (fs.js:348:35)
      at Context.it (test\test-kitchen.ts:37:77)
      at processImmediate (internal/timers.js:443:21)
  4) 🚰 kitchen sink
       should check before fix:
      AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to: -1
      + expected - actual
      at Context.it (test\test-kitchen.ts:37:77)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
  5) 🚰 kitchen sink
       should fix:
     Error: Command failed: npm run fix
npm ERR! missing script: fix
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_logs\2019-05-04T06_01_41_951Z-debug.log
      at ChildProcess.exithandler (child_process.js:299:12)
      at maybeClose (internal/child_process.js:999:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
  6) 🚰 kitchen sink
       should check after fix:
     Error: Command failed: npm run check
npm ERR! missing script: check
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_logs\2019-05-04T06_01_43_066Z-debug.log
      at ChildProcess.exithandler (child_process.js:299:12)
      at maybeClose (internal/child_process.js:999:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
  7) 🚰 kitchen sink
       should build:
     Error: Command failed: npm run compile
npm ERR! missing script: compile
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_logs\2019-05-04T06_01_44_170Z-debug.log
      at ChildProcess.exithandler (child_process.js:299:12)
      at maybeClose (internal/child_process.js:999:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
  8) 🚰 kitchen sink
       should clean:
     Error: Command failed: npm run clean
npm ERR! missing script: clean
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_logs\2019-05-04T06_01_45_253Z-debug.log
      at ChildProcess.exithandler (child_process.js:299:12)
      at maybeClose (internal/child_process.js:999:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
```

**Comment by JustinBeckwith** [comment]
This is great.  Thank you so much!

**Comment by ofrobots** [comment]
We're looking into getting CirrusCI enabled on the org.. stay tuned.

**Comment by JustinBeckwith** [comment]
@fkorotkov thank you so much for drafting this up.  I think we've cleared out a few other roadblocks that should make this easier:
- Cirrus is enabled on our org now
- We wrapped up the path join changes in a separate commit (nice find)
- We cleaned up some bizarre node:8 failures related to temp directories and cirrus

Would you be willing to rebase and see where this comes out now?  Again - really, thank you for the work here.

**Comment by fkorotkov** [comment]
Doesn't seem to help 😪 I also noticed that `console.log(fs.readdirSync(path.join(stagingPath, 'kitchen')))` doesn't really log `tsconfig.json` being on the FS 🤔

**Comment by JustinBeckwith** [comment]
@fkorotkov feeling really good about this one now 😆 Mind giving us a rebase again here?

**Comment by JustinBeckwith** [comment]
@fkorotkov thank you so much for doing this, and being patient.  This is awesome!

**Comment by fkorotkov** [comment]
@JustinBeckwith awesome! Glad to help! Feel free to ping me with any related questions. 🙌

**Pull request merged**
