### PR TITLE
refactor: drop pify, and select dev dependencies

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This drops a few dependencies:
- Move to `util.promisify` instead of `pify` now that we dropped node 6
- Use `fs-extra`, which was already included, instead of `npc`
- Use `execSync` instead of `execa` 
- Drops unused dependencies and type packages

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@ofrobots is that windows test normally uh, passing?

**Comment by ofrobots** [comment]
@soldair was poking at it last, and I think got it to pass.

**Comment by soldair** [comment]
im pretty sure we did in fact get it to pass. i'll look into what happened with that

**Comment by soldair** [comment]
https://github.com/google/gts/pull/330

**Comment by JustinBeckwith** [comment]
I believe so.  In that case, I'll come back around and get this on #333

**Pull request merged**
