### PR TITLE
feat!: Update '.prettierrc.json' to include `trailingComma: "all"` to match internal Google config

### LINKED ISSUE #662: Enable more trailing commas, particularly in function parameters and calls
I'd like to suggest changing the Prettier trailingComma setting from es5 to all for the next gts release with breaking changes.

https://prettier.io/docs/en/options.html#trailing-commas

In particular, this would enable trailing commas in multiline function parameter lists and calls, which can help reduce commit diff noise.

The Prettier docs note that this requires ES2017 and TypeScript 2.7, but gts already specifies ES2018 and TypeScript 4.x.

### PR DESCRIPTION
**Pull request by calebegg**
fixes #662

### CODE REVIEW

**Comment by tonycoco** [comment]
Can we rebase this? Change looks good to me.

**Review by tonycoco — APPROVED** [review]
LGTM

**Comment by calebegg** [comment]
I am not good at git, my brain has been permanently disfigured by fifteen years of using nothing but Piper/Perforce. I think I screwed this up somehow even though I was following a github help page. If you want to help me that's fine, or if you want to just make the change yourself that's fine too. I've spent half an hour on this and I'm quite frustrated.

**Comment by calebegg** [comment]
Ok I think I fixed it (thanks again for the help!)

**Review by tonycoco — APPROVED** [review]

**Comment by tonycoco** [comment]
Note: the commit message needs to follow conventional commits. Can you amend your commit message?

This change will be messy for lots of repos using `gts` so we should think about bumping the release semver to align.

**Comment by calebegg** [comment]
Done

**Pull request merged**
